manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: philippkober
      url-base: https://github.com/philippkober
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: maxtouch-zephyr-module
      remote: philippkober
      revision: main
      path: modules/maxtouch
  self:
    path: config
